### PR TITLE
ENT-1836 version bump for edx-rbac

### PR DESCRIPTION
**Pull request by irfanuddinahmad**
Description: This PR upgrades the version of edx-rbac to 0.2.0

JIRA: https://openedx.atlassian.net/browse/ENT-1836

### CODE REVIEW

**Comment by irfanuddinahmad** [comment]
jenkins run all

**Comment by muhammad-ammar** [comment]
Initially build was failing due to [UnicodeEncodeError](https://travis-ci.org/edx/edx-enterprise-data/jobs/527402598) and the error itself was not helpful to debug what exactly is the issue, so `tox` verbosity was increased to see if we can find something helpful in the logs to fix the issue, after the increased verbosity logs show that [pyminizip install was failing](https://travis-ci.org/edx/edx-enterprise-data/jobs/527746967), then we unpin the `pyminizip` and it turns out that in latest version `compress` and `compress_multiple` function signature has [changed](https://github.com/smihica/pyminizip/commit/ed3cdaa80fd17a4a0fbf8aed49fbaf3708dcc9c3) and test are failing, finally fixed the tests and now the build is green. But still unsure why the build was failing in the first place?

@brittneyexline Any thoughts on this? Any idea why we pinned the `pyminizip`? Can you please review the changes?

**Review by saleem-latif — APPROVED** [review]

**Review by muhammad-ammar — APPROVED** [review]
👍

**Review by mushtaqak — APPROVED** [review]
Looks good 👍

**Pull request merged**
